var fibonacci = [1,2];
var calcFibonacci = function() {
  for(i=0;i<100;i++) {
       var y=i+1;
  x=fibonacci[i]+fibonacci[y];
  if(x<4000000) {
  fibonacci.push(x);
  }
  }  
};
calcFibonacci();
console.log("Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:");
for(z=0;z<10;z++){
    console.log(fibonacci[z]);
}
console.log("PROBLEM: By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.");
var solution = 0;
for(i=0;i<100;i++) {
var evenFibonacci = fibonacci[i];
if (evenFibonacci % 2 === 0) {
solution += evenFibonacci;
}
}
console.log("SOLUTION: The sum of the even-valued terms in the Fibonacci sequence, whose values do not exceed four million is " + solution);